Fixed duplicate timestamps causing pagination test failure #156
ostafen/clover pull request #157
Opened 2024-09-20 20:05 UTC by ahmed-hossam28

2024-09-20 20:37 UTC, ostafen commented on db_test.go
> +			// Old code that caused duplicates:
I think this comments here just add noise

2024-09-20 20:38 UTC, ostafen commented on db_test.go
> +			// New code to ensure unique timestamps:
This comment makes sense, but there is no need to mention about what "old code" was doing

2024-09-20 20:39 UTC, ostafen commented on db_test.go
> +	// Retrieve all documents from the collection
Let's remove `checkUniqueTimestamps`, it sounds something useful only for debugging during development.

2024-09-20 20:39 UTC, ostafen reviewed
Thanks for the PR, @ahmed-hossam28. Added some comments.

2024-09-20 20:50 UTC, ahmed-hossam28 commented
Thank you @ostafen  for your efforts too, I will resolve them.

2024-09-20 21:02 UTC, ahmed-hossam28 commented
@ostafen, I have removed the unnecessary comments and the checkUniqueTimestamps function as suggested.

2024-09-21 02:00 UTC, ostafen commented on db_test.go
> +			// doc.Set("timestamp", time.Now())
Please remove all the comments

2024-09-21 02:01 UTC, ostafen commented on db_test.go
> +			// New code to ensure unique timestamps:
You can leave this one, but rephrase it to not mention "old code"

2024-09-21 02:01 UTC, ostafen requested changes
Added some more comments

2024-09-21 11:25 UTC, ahmed-hossam28 commented
Thank you @ostafen for your feedback, i updated the comments.

2024-09-21 11:29 UTC, ostafen approved these changes

2024-09-21 11:29 UTC, ostafen commented
Looks good now, thanks for your patience!

2024-09-21 11:39 UTC, merged